import type { Paper1Lesson } from "./types";

const loaders: Record<string, () => Promise<{ default: unknown }>> = {
  "units-and-magnitudes": () => import("@/content/paper1/lessons/units-and-magnitudes.json"),
  "number-systems": () => import("@/content/paper1/lessons/number-systems.json"),
  "signed-arithmetic": () => import("@/content/paper1/lessons/signed-arithmetic.json"),
  "character-encoding": () => import("@/content/paper1/lessons/character-encoding.json"),
  "bitmap-storage": () => import("@/content/paper1/lessons/bitmap-storage.json"),
  "vector-graphics": () => import("@/content/paper1/lessons/vector-graphics.json"),
  "sound-sampling": () => import("@/content/paper1/lessons/sound-sampling.json"),
  "compression": () => import("@/content/paper1/lessons/compression.json"),
  "network-foundations": () => import("@/content/paper1/lessons/network-foundations.json"),
  "network-models": () => import("@/content/paper1/lessons/network-models.json"),
  "network-topologies": () => import("@/content/paper1/lessons/network-topologies.json"),
  "cloud-computing": () => import("@/content/paper1/lessons/cloud-computing.json"),
  "transmission-media": () => import("@/content/paper1/lessons/transmission-media.json"),
  "network-hardware": () => import("@/content/paper1/lessons/network-hardware.json"),
  "ethernet": () => import("@/content/paper1/lessons/ethernet.json"),
  "streaming": () => import("@/content/paper1/lessons/streaming.json"),
  "ip-addressing": () => import("@/content/paper1/lessons/ip-addressing.json"),
  "web-url-dns": () => import("@/content/paper1/lessons/web-url-dns.json"),
  "computer-organisation": () => import("@/content/paper1/lessons/computer-organisation.json"),
  "device-principles": () => import("@/content/paper1/lessons/device-principles.json"),
  "embedded-control": () => import("@/content/paper1/lessons/embedded-control.json"),
  "memory-technologies": () => import("@/content/paper1/lessons/memory-technologies.json"),
  "logic-gates": () => import("@/content/paper1/lessons/logic-gates.json"),
  "logic-design": () => import("@/content/paper1/lessons/logic-design.json"),
  "cpu-architecture": () => import("@/content/paper1/lessons/cpu-architecture.json"),
  "performance-ports": () => import("@/content/paper1/lessons/performance-ports.json"),
  "fetch-execute-interrupts": () => import("@/content/paper1/lessons/fetch-execute-interrupts.json"),
  "assembly-translation": () => import("@/content/paper1/lessons/assembly-translation.json"),
  "addressing-modes": () => import("@/content/paper1/lessons/addressing-modes.json"),
  "assembly-tracing": () => import("@/content/paper1/lessons/assembly-tracing.json"),
  "bit-shifts": () => import("@/content/paper1/lessons/bit-shifts.json"),
  "bit-masking": () => import("@/content/paper1/lessons/bit-masking.json"),
  "operating-systems": () => import("@/content/paper1/lessons/operating-systems.json"),
  "utilities-libraries": () => import("@/content/paper1/lessons/utilities-libraries.json"),
  "translators": () => import("@/content/paper1/lessons/translators.json"),
  "ide-tools": () => import("@/content/paper1/lessons/ide-tools.json"),
  "security-foundations": () => import("@/content/paper1/lessons/security-foundations.json"),
  "threats-protection": () => import("@/content/paper1/lessons/threats-protection.json"),
  "validation": () => import("@/content/paper1/lessons/validation.json"),
  "verification-transfer": () => import("@/content/paper1/lessons/verification-transfer.json"),
  "professional-ethics": () => import("@/content/paper1/lessons/professional-ethics.json"),
  "copyright-licences": () => import("@/content/paper1/lessons/copyright-licences.json"),
  "ai-impacts": () => import("@/content/paper1/lessons/ai-impacts.json"),
  "relational-foundations": () => import("@/content/paper1/lessons/relational-foundations.json"),
  "keys-relationships": () => import("@/content/paper1/lessons/keys-relationships.json"),
  "normalisation": () => import("@/content/paper1/lessons/normalisation.json"),
  "dbms": () => import("@/content/paper1/lessons/dbms.json"),
  "sql-foundations": () => import("@/content/paper1/lessons/sql-foundations.json"),
  "sql-ddl": () => import("@/content/paper1/lessons/sql-ddl.json"),
  "sql-dml": () => import("@/content/paper1/lessons/sql-dml.json"),
};

export async function getPaper1Lesson(slug: string): Promise<Paper1Lesson | undefined> {
  const loader = loaders[slug];
  return loader ? (await loader()).default as Paper1Lesson : undefined;
}

export const implementedPaper1Slugs = Object.freeze(Object.keys(loaders));
