"use client";

import { useId, useRef, useState, type CSSProperties, type ReactNode } from "react";
import { ArrowLeft, ArrowRight, RotateCcw } from "lucide-react";
import { Button, Select } from "@/app/components/algocore-ui";
import {
  SECURITY_INCIDENTS,
  THREAT_PATHS,
  VALIDATION_FIXTURES,
  VERIFICATION_FIXTURES,
  securityIncidentFrames,
  threatProtectionFrames,
  validationFrames,
  verificationFrames,
  verificationFacts,
  type SecurityIncident,
  type SecurityProperty,
  type ThreatPath,
  type ValidationFixture,
  type ValidationRule,
  type VerificationFixture,
  type VerificationMethod,
} from "@/app/lib/paper1/chapter6-models";
import type { Paper1Locale } from "@/app/lib/paper1/types";
import styles from "./Chapter6VisualLab.module.css";

type LocalText = Readonly<{ en: string; vi: string }>;
type ReceiptEntry = Readonly<{ label: string; value: string | number; current?: boolean }>;
type Scene = Readonly<{ sceneId: string; title: string; explanation: string; graphic: ReactNode; receipt: readonly ReceiptEntry[] }>;
type Prediction = Readonly<{ prompt: string; choices: readonly Readonly<{ id: string; label: string }>[]; correctChoiceId: string }>;
type ChainNode = Readonly<{ id: string; eyebrow: string; value: string }>;

const copy = (locale: Paper1Locale, en: string, vi: string) => locale === "vi" ? vi : en;
const local = (locale: Paper1Locale, value: LocalText) => value[locale];
const bool = (locale: Paper1Locale, value: boolean | null) => value === null ? "—" : value ? copy(locale, "Yes", "Có") : copy(locale, "No", "Không");
const join = (values: readonly string[]) => values.length ? values.join(" · ") : "—";

const PROPERTY_LABELS: Readonly<Record<SecurityProperty, LocalText>> = {
  security: { en: "Security", vi: "Bảo mật" },
  privacy: { en: "Privacy", vi: "Quyền riêng tư" },
  integrity: { en: "Integrity", vi: "Tính toàn vẹn" },
};

const SECURITY_COPY: Readonly<Record<SecurityIncident, Readonly<{
  title: LocalText; actor: LocalText; rights: LocalText; purpose: LocalText; action: LocalText;
  observed: LocalText; target: LocalText; evidence: LocalText; limitation: LocalText;
}>>> = {
  "stranger-read": {
    title: { en: "A stranger reads a student record", vi: "Người lạ đọc hồ sơ học sinh" },
    actor: { en: "Unknown visitor", vi: "Khách không rõ danh tính" },
    rights: { en: "No right to open the record", vi: "Không có quyền mở hồ sơ" },
    purpose: { en: "No authorised purpose", vi: "Không có mục đích được cho phép" },
    action: { en: "Requests and reads the student record", vi: "Yêu cầu và đọc hồ sơ học sinh" },
    observed: { en: "Access granted; personal record read; value unchanged", vi: "Được truy cập; hồ sơ cá nhân bị đọc; giá trị không đổi" },
    target: { en: "Personal data and the system access path", vi: "Dữ liệu cá nhân và đường truy cập hệ thống" },
    evidence: { en: "An unauthorised actor read personal data.", vi: "Một chủ thể không được phép đã đọc dữ liệu cá nhân." },
    limitation: { en: "One login screen does not prove total security.", vi: "Một màn hình đăng nhập không chứng minh hệ thống an toàn tuyệt đối." },
  },
  "purpose-overshare": {
    title: { en: "An authorised app shares beyond its purpose", vi: "Ứng dụng có quyền chia sẻ vượt mục đích" },
    actor: { en: "Authorised school app", vi: "Ứng dụng trường học đã được cấp quyền" },
    rights: { en: "May read for progress reporting only", vi: "Chỉ được đọc để lập báo cáo tiến độ" },
    purpose: { en: "Prepare a student progress report", vi: "Lập báo cáo tiến độ học sinh" },
    action: { en: "Shares the record beyond the stated purpose", vi: "Chia sẻ hồ sơ vượt quá mục đích đã nêu" },
    observed: { en: "Valid read access; later disclosure was outside the purpose", vi: "Quyền đọc hợp lệ; việc tiết lộ sau đó nằm ngoài mục đích" },
    target: { en: "Use and disclosure of personal data", vi: "Việc sử dụng và tiết lộ dữ liệu cá nhân" },
    evidence: { en: "Valid access did not authorise every later disclosure.", vi: "Quyền truy cập hợp lệ không cho phép mọi lần tiết lộ sau đó." },
    limitation: { en: "Authentication does not authorise every use of data.", vi: "Xác thực không cho phép mọi cách sử dụng dữ liệu." },
  },
  "mark-transposition": {
    title: { en: "Mark 80 is stored as 08", vi: "Điểm 80 được lưu thành 08" },
    actor: { en: "Authorised teacher", vi: "Giáo viên đã được cấp quyền" },
    rights: { en: "May write marks for the assigned class", vi: "Được ghi điểm cho lớp được phân công" },
    purpose: { en: "Record the assessed mark", vi: "Ghi lại điểm đã chấm" },
    action: { en: "Saves 08 instead of source value 80", vi: "Lưu 08 thay cho giá trị nguồn 80" },
    observed: { en: "Write completed; stored value changed from 80 to 08", vi: "Đã ghi; giá trị lưu đổi từ 80 thành 08" },
    target: { en: "Input process and stored mark", vi: "Quy trình nhập và điểm đã lưu" },
    evidence: { en: "The stored value no longer matches the supplied source.", vi: "Giá trị đã lưu không còn khớp với nguồn được cung cấp." },
    limitation: { en: "This fixture alone does not show unauthorised access.", vi: "Riêng tình huống này không cho thấy truy cập trái phép." },
  },
};

const THREAT_COPY: Readonly<Record<ThreatPath, Readonly<{
  title: LocalText; actor: LocalText; step: LocalText; boundary: LocalText; control: LocalText; point: LocalText;
  asset: LocalText; unprotectedOutcome: LocalText; protectedOutcome: LocalText; unprotectedState: LocalText;
  protectedState: LocalText; unprotectedRisk: LocalText; protectedRisk: LocalText;
}>>> = {
  phishing: { title: { en: "Phishing message", vi: "Tin nhắn phishing" }, actor: { en: "Message impersonating school support", vi: "Tin nhắn giả mạo bộ phận hỗ trợ trường" }, step: { en: "A deceptive message asks the user to follow a link", vi: "Tin nhắn đánh lừa yêu cầu người dùng mở liên kết" }, boundary: { en: "User decision and account authentication", vi: "Quyết định của người dùng và xác thực tài khoản" }, control: { en: "Verify origin, avoid the link and use MFA", vi: "Kiểm tra nguồn, tránh liên kết và dùng MFA" }, point: { en: "Before credential disclosure", vi: "Trước khi tiết lộ thông tin đăng nhập" }, asset: { en: "Student account", vi: "Tài khoản học sinh" }, unprotectedOutcome: { en: "The route reaches a credential request", vi: "Đường tấn công tới bước yêu cầu thông tin đăng nhập" }, protectedOutcome: { en: "The deceptive route is rejected", vi: "Đường dẫn lừa đảo bị từ chối" }, unprotectedState: { en: "Credential disclosed in this fixture", vi: "Thông tin đăng nhập bị tiết lộ trong tình huống này" }, protectedState: { en: "Credential not disclosed in this fixture", vi: "Thông tin đăng nhập không bị tiết lộ trong tình huống này" }, unprotectedRisk: { en: "Account misuse can follow", vi: "Có thể dẫn tới lạm dụng tài khoản" }, protectedRisk: { en: "User judgement and authentication configuration still matter", vi: "Phán đoán người dùng và cấu hình xác thực vẫn quan trọng" } },
  pharming: { title: { en: "Pharming redirection", vi: "Chuyển hướng pharming" }, actor: { en: "Fraudulent site route", vi: "Đường dẫn tới trang giả mạo" }, step: { en: "Name resolution leads to a fraudulent site", vi: "Phân giải tên dẫn tới trang giả mạo" }, boundary: { en: "Trusted name resolution and site identity", vi: "Phân giải tên đáng tin cậy và danh tính trang" }, control: { en: "Trusted DNS/router configuration and certificate check", vi: "Cấu hình DNS/router đáng tin cậy và kiểm tra chứng chỉ" }, point: { en: "Before sensitive data is submitted", vi: "Trước khi gửi dữ liệu nhạy cảm" }, asset: { en: "Login data", vi: "Dữ liệu đăng nhập" }, unprotectedOutcome: { en: "The fraudulent destination is accepted", vi: "Đích giả mạo được chấp nhận" }, protectedOutcome: { en: "A site-identity mismatch is exposed", vi: "Sai lệch danh tính trang được phát hiện" }, unprotectedState: { en: "Login data entered at the fraudulent site", vi: "Dữ liệu đăng nhập được nhập vào trang giả" }, protectedState: { en: "Submission stopped in this fixture", vi: "Việc gửi dữ liệu bị dừng trong tình huống này" }, unprotectedRisk: { en: "Data disclosure can follow", vi: "Có thể dẫn tới tiết lộ dữ liệu" }, protectedRisk: { en: "A familiar-looking page is never proof by itself", vi: "Giao diện quen thuộc không tự chứng minh trang là thật" } },
  virus: { title: { en: "Virus in a downloaded file", vi: "Virus trong tệp tải xuống" }, actor: { en: "Virus hosted in a file", vi: "Virus nằm trong một tệp" }, step: { en: "The host file attempts execution and replication", vi: "Tệp chủ cố thực thi và nhân bản virus" }, boundary: { en: "Endpoint execution", vi: "Điểm thực thi trên thiết bị" }, control: { en: "Updated antivirus, quarantine and least privilege", vi: "Antivirus đã cập nhật, cách ly và quyền tối thiểu" }, point: { en: "Before or during execution", vi: "Trước hoặc trong khi thực thi" }, asset: { en: "Files and system operation", vi: "Tệp và hoạt động hệ thống" }, unprotectedOutcome: { en: "The malicious file executes", vi: "Tệp độc hại được thực thi" }, protectedOutcome: { en: "The suspicious file is quarantined", vi: "Tệp đáng ngờ bị cách ly" }, unprotectedState: { en: "Data and operation are exposed to change", vi: "Dữ liệu và hoạt động có nguy cơ bị thay đổi" }, protectedState: { en: "The fixture is isolated before execution", vi: "Tình huống được cách ly trước khi thực thi" }, unprotectedRisk: { en: "Damage or replication can follow", vi: "Có thể xảy ra phá hoại hoặc nhân bản" }, protectedRisk: { en: "No antivirus is guaranteed to detect every sample", vi: "Không antivirus nào được bảo đảm phát hiện mọi mẫu" } },
  spyware: { title: { en: "Covert spyware collection", vi: "Spyware bí mật thu thập dữ liệu" }, actor: { en: "Covert monitoring software", vi: "Phần mềm giám sát bí mật" }, step: { en: "Software attempts secret collection and exfiltration", vi: "Phần mềm cố thu thập và gửi dữ liệu bí mật" }, boundary: { en: "Endpoint permissions and outbound monitoring", vi: "Quyền trên thiết bị và giám sát dữ liệu gửi ra" }, control: { en: "Anti-spyware, permission review and least privilege", vi: "Anti-spyware, rà soát quyền và quyền tối thiểu" }, point: { en: "At installation, permission and monitoring checks", vi: "Tại các kiểm tra cài đặt, quyền và giám sát" }, asset: { en: "Private activity and data", vi: "Hoạt động và dữ liệu riêng tư" }, unprotectedOutcome: { en: "Covert collection continues", vi: "Việc thu thập bí mật tiếp diễn" }, protectedOutcome: { en: "The covert collector is detected and restricted", vi: "Công cụ thu thập bí mật bị phát hiện và hạn chế" }, unprotectedState: { en: "Private data collected in this fixture", vi: "Dữ liệu riêng tư bị thu thập trong tình huống này" }, protectedState: { en: "Collection stopped in this fixture", vi: "Việc thu thập bị dừng trong tình huống này" }, unprotectedRisk: { en: "Secret disclosure can follow", vi: "Có thể dẫn tới tiết lộ bí mật" }, protectedRisk: { en: "Endpoint and user decisions remain relevant", vi: "Thiết bị đầu cuối và quyết định người dùng vẫn quan trọng" } },
  "unauthorised-access": { title: { en: "Unauthorised access request", vi: "Yêu cầu truy cập trái phép" }, actor: { en: "Unauthorised account request", vi: "Yêu cầu từ tài khoản không được phép" }, step: { en: "The request attempts to reach staff records", vi: "Yêu cầu cố truy cập hồ sơ nhân viên" }, boundary: { en: "Network, identity and authorisation", vi: "Mạng, danh tính và phân quyền" }, control: { en: "Account/password, authentication, firewall and access rights", vi: "Tài khoản/mật khẩu, xác thực, firewall và quyền truy cập" }, point: { en: "At network entry, then at the resource operation", vi: "Tại điểm vào mạng, rồi tại thao tác trên tài nguyên" }, asset: { en: "Staff records", vi: "Hồ sơ nhân viên" }, unprotectedOutcome: { en: "The unauthorised request reaches the record", vi: "Yêu cầu trái phép tới được hồ sơ" }, protectedOutcome: { en: "The request is blocked or denied by rights", vi: "Yêu cầu bị chặn hoặc từ chối theo quyền" }, unprotectedState: { en: "The record is readable or changeable in this fixture", vi: "Hồ sơ có thể bị đọc hoặc sửa trong tình huống này" }, protectedState: { en: "The record remains restricted", vi: "Hồ sơ vẫn bị giới hạn truy cập" }, unprotectedRisk: { en: "Viewing, copying, changing, deleting or disruption can follow", vi: "Có thể dẫn tới xem, sao chép, sửa, xóa hoặc gián đoạn" }, protectedRisk: { en: "An authenticated identity still needs correct authorisation", vi: "Danh tính đã xác thực vẫn cần được phân quyền đúng" } },
  "plaintext-interception": { title: { en: "Plaintext interception", vi: "Chặn bắt plaintext" }, actor: { en: "Network observer", vi: "Chủ thể quan sát trên mạng" }, step: { en: "The observer captures transmitted content", vi: "Chủ thể quan sát thu được nội dung đang truyền" }, boundary: { en: "Confidentiality of data in transit", vi: "Tính bí mật của dữ liệu khi truyền" }, control: { en: "Encryption with protected keys and endpoints", vi: "Mã hóa cùng khóa và endpoint được bảo vệ" }, point: { en: "Before data crosses an untrusted network", vi: "Trước khi dữ liệu đi qua mạng không tin cậy" }, asset: { en: "Message content", vi: "Nội dung thông điệp" }, unprotectedOutcome: { en: "Captured plaintext is readable", vi: "Plaintext bị thu có thể đọc được" }, protectedOutcome: { en: "Captured ciphertext is unreadable without the key", vi: "Ciphertext bị thu không đọc được nếu thiếu khóa" }, unprotectedState: { en: "The observer understands the content", vi: "Chủ thể quan sát hiểu được nội dung" }, protectedState: { en: "The observer cannot understand the content in this fixture", vi: "Chủ thể quan sát không hiểu được nội dung trong tình huống này" }, unprotectedRisk: { en: "Privacy loss can follow", vi: "Có thể dẫn tới mất quyền riêng tư" }, protectedRisk: { en: "Endpoint or key compromise remains possible", vi: "Endpoint hoặc khóa vẫn có thể bị xâm phạm" } },
  "changed-signed-message": { title: { en: "Changed signed message", vi: "Thông điệp đã ký bị thay đổi" }, actor: { en: "Message alteration in transit", vi: "Thay đổi thông điệp khi truyền" }, step: { en: "Signed message content is changed", vi: "Nội dung thông điệp đã ký bị thay đổi" }, boundary: { en: "Message origin and integrity", vi: "Nguồn gốc và tính toàn vẹn thông điệp" }, control: { en: "Verify the digital signature with a trusted public key", vi: "Xác minh chữ ký số bằng public key đáng tin cậy" }, point: { en: "Before the message is trusted", vi: "Trước khi tin cậy thông điệp" }, asset: { en: "Message integrity", vi: "Tính toàn vẹn thông điệp" }, unprotectedOutcome: { en: "The changed message is treated as trusted", vi: "Thông điệp đã đổi bị coi là đáng tin cậy" }, protectedOutcome: { en: "Signature verification is invalid", vi: "Kết quả xác minh chữ ký không hợp lệ" }, unprotectedState: { en: "The alteration is not exposed in this fixture", vi: "Sự thay đổi không bị phát hiện trong tình huống này" }, protectedState: { en: "Change or untrusted origin is flagged", vi: "Thay đổi hoặc nguồn không đáng tin bị đánh dấu" }, unprotectedRisk: { en: "Changed content can be accepted", vi: "Nội dung đã đổi có thể được chấp nhận" }, protectedRisk: { en: "Signing does not encrypt message content", vi: "Ký số không mã hóa nội dung thông điệp" } },
  "biometric-access": { title: { en: "Biometric identity and access rights", vi: "Danh tính sinh trắc học và quyền truy cập" }, actor: { en: "Person presenting a biometric sample", vi: "Người cung cấp mẫu sinh trắc học" }, step: { en: "The captured sample is compared with an enrolled template", vi: "Mẫu thu được được so với template đã đăng ký" }, boundary: { en: "Identity, then resource authorisation", vi: "Danh tính, sau đó phân quyền tài nguyên" }, control: { en: "Biometric template match, then access-right check", vi: "So khớp template sinh trắc học, rồi kiểm tra quyền truy cập" }, point: { en: "Identity check followed by policy check", vi: "Kiểm tra danh tính rồi kiểm tra chính sách" }, asset: { en: "Medical record", vi: "Hồ sơ y tế" }, unprotectedOutcome: { en: "The identity claim is not checked", vi: "Tuyên bố danh tính không được kiểm tra" }, protectedOutcome: { en: "Identity matches, then policy denies record access", vi: "Danh tính khớp, sau đó chính sách từ chối truy cập hồ sơ" }, unprotectedState: { en: "The record is exposed without identity evidence", vi: "Hồ sơ bị lộ khi chưa có bằng chứng danh tính" }, protectedState: { en: "The record remains restricted by access rights", vi: "Hồ sơ vẫn bị giới hạn bởi quyền truy cập" }, unprotectedRisk: { en: "Impersonation and overbroad access can follow", vi: "Có thể xảy ra giả mạo và truy cập quá rộng" }, protectedRisk: { en: "False acceptance, false rejection and policy errors remain possible", vi: "Vẫn có thể chấp nhận sai, từ chối sai hoặc lỗi chính sách" } },
};

const RULE_COPY: Readonly<Record<ValidationRule, Readonly<{ title: LocalText; field: LocalText; condition: LocalText; calculationPass: LocalText; calculationFail: LocalText; benefit: LocalText; limitPass: LocalText; limitFail: LocalText }>>> = {
  range: { title: { en: "Range check", vi: "Kiểm tra miền" }, field: { en: "Student age", vi: "Tuổi học sinh" }, condition: { en: "18 ≤ age ≤ 120, including both boundaries", vi: "18 ≤ tuổi ≤ 120, gồm cả hai biên" }, calculationPass: { en: "18 is exactly the inclusive lower boundary", vi: "18 đúng bằng biên dưới được tính" }, calculationFail: { en: "17 is below the lower boundary 18", vi: "17 nhỏ hơn biên dưới 18" }, benefit: { en: "Rejects values outside both declared bounds", vi: "Loại giá trị nằm ngoài cả hai biên đã khai báo" }, limitPass: { en: "A value inside the range may still describe the wrong student", vi: "Giá trị trong miền vẫn có thể mô tả sai học sinh" }, limitFail: { en: "A failed rule identifies nonconformance, not why the error happened", vi: "Không đạt quy tắc chỉ cho biết không phù hợp, không cho biết nguyên nhân lỗi" } },
  format: { title: { en: "Format check", vi: "Kiểm tra định dạng" }, field: { en: "Exam date", vi: "Ngày thi" }, condition: { en: "Exact pattern DD/MM/YYYY", vi: "Mẫu chính xác DD/MM/YYYY" }, calculationPass: { en: "Two digits / two digits / four digits", vi: "Hai chữ số / hai chữ số / bốn chữ số" }, calculationFail: { en: "YYYY-MM-DD does not match DD/MM/YYYY", vi: "YYYY-MM-DD không khớp DD/MM/YYYY" }, benefit: { en: "Rejects input that does not match the declared character pattern", vi: "Loại input không khớp mẫu ký tự đã khai báo" }, limitPass: { en: "A matching pattern does not prove the intended real-world date", vi: "Khớp mẫu không chứng minh đây là ngày thực tế mong muốn" }, limitFail: { en: "Formatting a displayed value is not input validation", vi: "Định dạng giá trị hiển thị không phải validation input" } },
  length: { title: { en: "Length check", vi: "Kiểm tra độ dài" }, field: { en: "Student code", vi: "Mã học sinh" }, condition: { en: "Exactly 8 characters", vi: "Đúng 8 ký tự" }, calculationPass: { en: "Character count = 8", vi: "Số ký tự = 8" }, calculationFail: { en: "Character count = 7", vi: "Số ký tự = 7" }, benefit: { en: "Rejects values with the wrong character count", vi: "Loại giá trị có số ký tự không đúng" }, limitPass: { en: "Correct length does not prove the code belongs to the student", vi: "Đúng độ dài không chứng minh mã thuộc về học sinh" }, limitFail: { en: "Length alone does not inspect the meaning of characters", vi: "Chỉ độ dài không kiểm tra ý nghĩa của ký tự" } },
  presence: { title: { en: "Presence check", vi: "Kiểm tra hiện diện" }, field: { en: "Required student name", vi: "Tên học sinh bắt buộc" }, condition: { en: "Trim whitespace; the result must not be empty", vi: "Bỏ khoảng trắng đầu/cuối; kết quả không được rỗng" }, calculationPass: { en: "Trimmed length = 4", vi: "Độ dài sau khi trim = 4" }, calculationFail: { en: "Trimmed length = 0", vi: "Độ dài sau khi trim = 0" }, benefit: { en: "Rejects a required field that is empty", vi: "Loại trường bắt buộc bị để trống" }, limitPass: { en: "Present content can still be wrong", vi: "Nội dung hiện diện vẫn có thể sai" }, limitFail: { en: "Presence does not check meaning or accuracy", vi: "Presence không kiểm tra ý nghĩa hoặc độ chính xác" } },
  existence: { title: { en: "Existence check", vi: "Kiểm tra tồn tại" }, field: { en: "Course code", vi: "Mã khóa học" }, condition: { en: "Value must appear in {CS01, CS02, CS03}", vi: "Giá trị phải có trong {CS01, CS02, CS03}" }, calculationPass: { en: "CS02 is a member of the fixed table", vi: "CS02 là phần tử của bảng cố định" }, calculationFail: { en: "CS09 is absent from the fixed table", vi: "CS09 không có trong bảng cố định" }, benefit: { en: "Rejects a value absent from the declared data store", vi: "Loại giá trị không có trong kho dữ liệu đã khai báo" }, limitPass: { en: "Membership does not prove that a person or claim is genuine", vi: "Có trong bảng không chứng minh người hoặc lời khai là thật" }, limitFail: { en: "The result depends on the authorised list being current", vi: "Kết quả phụ thuộc danh sách được phép có còn cập nhật hay không" } },
  limit: { title: { en: "Limit check", vi: "Kiểm tra giới hạn" }, field: { en: "Upload size in MiB", vi: "Kích thước tải lên theo MiB" }, condition: { en: "Size ≤ 5 MiB; this rule has one upper bound", vi: "Kích thước ≤ 5 MiB; quy tắc này có một biên trên" }, calculationPass: { en: "5 equals the inclusive upper limit", vi: "5 đúng bằng giới hạn trên được tính" }, calculationFail: { en: "5.1 is greater than the upper limit 5", vi: "5,1 lớn hơn giới hạn trên 5" }, benefit: { en: "Rejects values beyond one declared bound", vi: "Loại giá trị vượt một biên đã khai báo" }, limitPass: { en: "A limit check has one bound; a range check has two", vi: "Limit check có một biên; range check có hai biên" }, limitFail: { en: "Failing the size limit says nothing about file contents", vi: "Không đạt giới hạn kích thước không cho biết nội dung tệp" } },
  "check-digit": { title: { en: "Check digit validation", vi: "Validation bằng chữ số kiểm tra" }, field: { en: "Teaching identifier", vi: "Mã định danh minh họa" }, condition: { en: "Digits 314159 use weights 7,6,5,4,3,2; check = 11 − (sum mod 11)", vi: "Các chữ số 314159 dùng trọng số 7,6,5,4,3,2; check = 11 − (tổng mod 11)" }, calculationPass: { en: "Products sum to 84; remainder 7; expected digit 4; received 4", vi: "Tổng tích bằng 84; số dư 7; chữ số cần có là 4; nhận được 4" }, calculationFail: { en: "Products sum to 84; expected digit 4; received 5", vi: "Tổng tích bằng 84; chữ số cần có là 4; nhận được 5" }, benefit: { en: "Detects many likely entry errors covered by this declared algorithm", vi: "Phát hiện nhiều lỗi nhập liệu thuộc phạm vi thuật toán đã khai báo" }, limitPass: { en: "A matching digit does not guarantee that the complete number is correct", vi: "Chữ số khớp không bảo đảm toàn bộ số là đúng" }, limitFail: { en: "This is one classroom rule, not a universal barcode algorithm", vi: "Đây là một quy tắc lớp học, không phải thuật toán barcode phổ quát" } },
};

const METHOD_LABELS: Readonly<Record<VerificationMethod, LocalText>> = {
  visual: { en: "Visual check", vi: "Kiểm tra trực quan" },
  "double-entry": { en: "Double entry", vi: "Nhập hai lần" },
  "byte-parity": { en: "Byte parity", vi: "Parity byte" },
  "block-parity": { en: "Block parity", vi: "Parity khối" },
  checksum: { en: "Checksum", vi: "Checksum" },
};

const FIXTURE_LABELS: Readonly<Record<VerificationFixture, LocalText>> = {
  match: { en: "Matching values", vi: "Các giá trị khớp nhau" },
  difference: { en: "One transcription difference", vi: "Một khác biệt khi chép" },
  "same-wrong-twice": { en: "The same wrong value twice", vi: "Cùng một giá trị sai ở cả hai lần" },
  "no-change": { en: "No transmitted change", vi: "Không có thay đổi khi truyền" },
  "one-flip": { en: "One flipped bit", vi: "Một bit bị đảo" },
  "two-flips": { en: "Two flipped bits", vi: "Hai bit bị đảo" },
  rectangle: { en: "Four-corner rectangle", vi: "Bốn góc của hình chữ nhật" },
  "one-changed-byte": { en: "One changed byte", vi: "Một byte bị thay đổi" },
  compensating: { en: "+1/−1 compensating changes", vi: "Hai thay đổi bù nhau +1/−1" },
};

const METHOD_CONVENTION: Readonly<Record<VerificationMethod, LocalText>> = {
  visual: { en: "Compare the entered value with the visible source", vi: "So sánh giá trị đã nhập với nguồn nhìn thấy" },
  "double-entry": { en: "Enter the same source independently twice, then compare", vi: "Nhập độc lập cùng một nguồn hai lần, rồi so sánh" },
  "byte-parity": { en: "Even parity; seven data bits and a rightmost parity bit at index 7", vi: "Parity chẵn; bảy data bit và parity bit bên phải ở index 7" },
  "block-parity": { en: "Even row and column parity in a 4×4 block; data is the top-left 3×3", vi: "Parity chẵn theo hàng và cột trong khối 4×4; data là vùng 3×3 phía trên trái" },
  checksum: { en: "Direct sum of bytes modulo 256", vi: "Tổng trực tiếp các byte modulo 256" },
};

function EvidenceChain({ locale, nodes, activeIds, ticket }: { readonly locale: Paper1Locale; readonly nodes: readonly ChainNode[]; readonly activeIds: readonly string[]; readonly ticket: string }) {
  return <div className={styles.evidenceChain} role="img" aria-label={copy(locale, `Evidence chain; current evidence ${ticket}`, `Chuỗi bằng chứng; bằng chứng hiện tại ${ticket}`)}>
    {nodes.map((node, index) => <div className={styles.chainWrap} key={node.id}>
      <div className={styles.chainNode} data-active={activeIds.includes(node.id) || undefined} data-applied={activeIds.includes(node.id) && index < nodes.length - 1 || undefined}>
        <small>{node.eyebrow}</small><strong>{node.value}</strong>{activeIds.includes(node.id) ? <b aria-hidden="true">{ticket}</b> : null}
      </div>{index < nodes.length - 1 ? <i aria-hidden="true">→</i> : null}
    </div>)}
  </div>;
}

type JourneyProps = Readonly<{ locale: Paper1Locale; visualId: string; title: string; intro: string; controls: ReactNode; prediction: Prediction; scenes: readonly Scene[]; stateKey: string; onReset: () => void }>;

function Journey(props: JourneyProps) {
  return <section className={styles.lab} data-paper1-visual={props.visualId} aria-labelledby={`${props.visualId}-title`}>
    <header className={styles.header}><span>CHAPTER 6 · EVIDENCE CHAIN · {props.visualId}</span><h3 id={`${props.visualId}-title`}>{props.title}</h3><p>{props.intro}</p></header>
    <div className={styles.controls}>{props.controls}<div className={styles.controlNote}><strong>{copy(props.locale, "Inspect the declared fixture", "Quan sát tình huống đã khai báo")}</strong><span>{copy(props.locale, "Changing a selector clears the prediction and returns to evidence 01.", "Đổi lựa chọn sẽ xóa dự đoán và trở về bằng chứng 01.")}</span></div></div>
    <JourneySession key={props.stateKey} {...props} />
  </section>;
}

function JourneySession({ locale, prediction, scenes, onReset }: JourneyProps) {
  const [step, setStep] = useState(0);
  const [choice, setChoice] = useState<string>();
  const radioName = useId();
  const legendRef = useRef<HTMLLegendElement>(null);
  const safeStep = Math.min(step, scenes.length - 1);
  const current = scenes[safeStep];
  const finished = safeStep === scenes.length - 1;
  const selected = prediction.choices.find((entry) => entry.id === choice);
  const expected = prediction.choices.find((entry) => entry.id === prediction.correctChoiceId);
  const reset = () => { onReset(); setStep(0); setChoice(undefined); requestAnimationFrame(() => legendRef.current?.focus()); };
  return <>
    <fieldset className={styles.prediction}><legend ref={legendRef} tabIndex={-1}>{copy(locale, "Predict before the evidence is revealed", "Dự đoán trước khi bằng chứng được mở")}</legend><p>{prediction.prompt}</p><div>{prediction.choices.map((entry) => <label key={entry.id}><input type="radio" name={radioName} checked={choice === entry.id} onChange={() => { setStep(0); setChoice(entry.id); }} /><span>{entry.label}</span></label>)}</div><small aria-live="polite">{choice ? copy(locale, "Prediction recorded. Next now reveals one evidence change at a time.", "Đã ghi dự đoán. Tiếp theo sẽ mở từng thay đổi bằng chứng.") : copy(locale, "Choose one answer to unlock evidence 01.", "Chọn một đáp án để mở bằng chứng 01.")}</small></fieldset>
    {choice ? <div className={styles.stage} data-scene-id={current.sceneId}>
      <div className={styles.meter} style={{ "--step-count": scenes.length } as CSSProperties} role="img" aria-label={copy(locale, `Evidence ${safeStep + 1} of ${scenes.length}`, `Bằng chứng ${safeStep + 1} trên ${scenes.length}`)}>{scenes.map((_, index) => <span key={index} data-current={index === safeStep || undefined} data-complete={index < safeStep || undefined} />)}</div>
      <div className={styles.instrument}><div className={styles.canvasWrap} tabIndex={0} aria-label={copy(locale, "Interactive evidence model", "Mô hình bằng chứng tương tác")}>{current.graphic}</div><aside className={styles.receipt} aria-label={copy(locale, "Evidence ledger", "Sổ bằng chứng")}><strong>{copy(locale, "EVIDENCE LEDGER", "SỔ BẰNG CHỨNG")}</strong><dl>{current.receipt.map((entry, index) => <div key={`${entry.label}-${index}`} data-current={entry.current || undefined}><dt><span>{index + 1}</span>{entry.label}</dt><dd>{entry.value}</dd></div>)}</dl></aside></div>
      <div className={styles.explanation} aria-live="polite" aria-atomic="true"><span>{copy(locale, `EVIDENCE ${String(safeStep + 1).padStart(2, "0")}`, `BẰNG CHỨNG ${String(safeStep + 1).padStart(2, "0")}`)}</span><h4>{current.title}</h4><p>{current.explanation}</p></div>
      <div className={styles.textEquivalent}><strong>{copy(locale, "Cumulative text equivalent", "Mô tả chữ tích lũy")}</strong><p>{copy(locale, "Every revealed value, calculation and limitation remains available without relying on colour, position or motion.", "Mọi giá trị, phép tính và giới hạn đã mở vẫn đọc được mà không phụ thuộc màu sắc, vị trí hoặc chuyển động.")}</p><ol>{scenes.slice(0, safeStep + 1).map((scene, sceneIndex) => <li key={scene.sceneId} aria-current={sceneIndex === safeStep ? "step" : undefined}><h5>{copy(locale, `Evidence ${sceneIndex + 1}`, `Bằng chứng ${sceneIndex + 1}`)} · {scene.title}</h5><p>{scene.explanation}</p><dl>{scene.receipt.map((entry, index) => <div key={`${entry.label}-${index}`}><dt>{entry.label}</dt><dd>{entry.value}</dd></div>)}</dl></li>)}</ol></div>
      {finished ? <aside className={styles.comparison} data-match={choice === prediction.correctChoiceId || undefined} aria-live="polite"><strong>{choice === prediction.correctChoiceId ? copy(locale, "Prediction matched the evidence", "Dự đoán khớp với bằng chứng") : copy(locale, "Revise the prediction from the evidence", "Hãy sửa dự đoán dựa trên bằng chứng")}</strong><dl><div><dt>{copy(locale, "You chose", "Bạn chọn")}</dt><dd>{selected?.label}</dd></div><div><dt>{copy(locale, "Evidence supports", "Bằng chứng hỗ trợ")}</dt><dd>{expected?.label}</dd></div></dl></aside> : null}
      <nav className={styles.navigation} aria-label={copy(locale, "Evidence controls", "Điều khiển bằng chứng")}><Button variant="secondary" disabled={safeStep === 0} onClick={() => setStep((value) => Math.max(0, value - 1))}><ArrowLeft size={17} aria-hidden="true" />{copy(locale, "Back", "Quay lại")}</Button><Button variant="quiet" onClick={reset}><RotateCcw size={17} aria-hidden="true" />{copy(locale, "Reset", "Đặt lại")}</Button><Button disabled={finished} onClick={() => setStep((value) => Math.min(scenes.length - 1, value + 1))}>{copy(locale, "Next", "Tiếp theo")}<ArrowRight size={17} aria-hidden="true" /></Button></nav>
    </div> : <div className={styles.lockedStage} role="status" aria-live="polite"><strong>{copy(locale, "Prediction gate", "Cổng dự đoán")}</strong><p>{copy(locale, "The diagram, ledger and verdict stay hidden until you choose a prediction.", "Sơ đồ, sổ bằng chứng và kết luận được giữ kín tới khi bạn chọn dự đoán.")}</p></div>}
  </>;
}

function SecurityLab({ locale }: { readonly locale: Paper1Locale }) {
  const defaults: SecurityIncident = "stranger-read";
  const [incident, setIncident] = useState<SecurityIncident>(defaults);
  const facts = SECURITY_INCIDENTS[incident];
  const c = SECURITY_COPY[incident];
  const frames = securityIncidentFrames(incident);
  const propertySet = facts.affectedProperties.join("+");
  const choiceSets = ["security+privacy", "privacy", "integrity", "security"];
  const scenes = frames.map((frame, index): Scene => {
    const observed = index >= 2 ? local(locale, c.observed) : copy(locale, "Not observed yet", "Chưa quan sát");
    const properties = index === 3 ? facts.affectedProperties.map((item) => local(locale, PROPERTY_LABELS[item])).join(" + ") : "—";
    const target = index === 3 ? local(locale, c.target) : "—";
    return { sceneId: `P1-L37-${incident}-${frame.id}`, title: [copy(locale, "Read the protected record", "Đọc hồ sơ được bảo vệ"), copy(locale, "Inspect the trust boundary", "Quan sát ranh giới tin cậy"), copy(locale, "Record what happened", "Ghi lại điều đã xảy ra"), copy(locale, "Qualify the affected properties", "Xác định các thuộc tính bị ảnh hưởng")][index], explanation: [copy(locale, `The original mark is 80. ${local(locale, c.rights)}. Authorised purpose: ${local(locale, c.purpose)}.`, `Điểm gốc là 80. ${local(locale, c.rights)}. Mục đích được phép: ${local(locale, c.purpose)}.`), copy(locale, `${local(locale, c.actor)} attempts this action: ${local(locale, c.action)}.`, `${local(locale, c.actor)} thực hiện: ${local(locale, c.action)}.`), local(locale, c.observed), `${local(locale, c.evidence)} ${local(locale, c.limitation)}`][index], graphic: <EvidenceChain locale={locale} activeIds={frame.activeIds} ticket={frame.ticket} nodes={[{ id: "record", eyebrow: copy(locale, "PROTECTED RECORD", "HỒ SƠ ĐƯỢC BẢO VỆ"), value: copy(locale, "Student mark = 80", "Điểm học sinh = 80") }, { id: "actor", eyebrow: copy(locale, "ACTOR", "CHỦ THỂ"), value: local(locale, c.actor) }, { id: "boundary", eyebrow: copy(locale, "BOUNDARY", "RANH GIỚI"), value: local(locale, c.action) }, { id: "observed-state", eyebrow: copy(locale, "OBSERVED STATE", "TRẠNG THÁI QUAN SÁT"), value: observed }, { id: "verdict", eyebrow: copy(locale, "QUALIFIED CLAIM", "KẾT LUẬN CÓ ĐIỀU KIỆN"), value: index === 3 ? properties : copy(locale, "Not revealed", "Chưa mở") }]} />, receipt: [{ label: copy(locale, "Actor rights", "Quyền của chủ thể"), value: local(locale, c.rights), current: index === 0 }, { label: copy(locale, "Authorised purpose", "Mục đích được phép"), value: local(locale, c.purpose), current: index === 0 }, { label: copy(locale, "Attempted action", "Hành động thử thực hiện"), value: index >= 1 ? local(locale, c.action) : "—", current: index === 1 }, { label: copy(locale, "Observed access/change", "Truy cập/thay đổi quan sát được"), value: observed, current: index === 2 }, { label: copy(locale, "Affected properties", "Thuộc tính bị ảnh hưởng"), value: properties, current: index === 3 }, { label: copy(locale, "Protection target", "Đối tượng cần bảo vệ"), value: target, current: index === 3 }, { label: copy(locale, "Limitation", "Giới hạn"), value: index === 3 ? local(locale, c.limitation) : "—", current: index === 3 }] };
  });
  return <Journey locale={locale} visualId="VIS-P1-L37" title={copy(locale, "Security, privacy and integrity evidence ledger", "Sổ bằng chứng về bảo mật, quyền riêng tư và toàn vẹn")} intro={copy(locale, "Trace the actor, permitted purpose, observed access or value change, then justify every affected property.", "Theo dõi chủ thể, mục đích được phép, truy cập hoặc thay đổi giá trị, rồi giải thích từng thuộc tính bị ảnh hưởng.")} stateKey={incident} onReset={() => setIncident(defaults)} controls={<Select id="p1-l37-incident" label={copy(locale, "Incident", "Sự cố")} value={incident} onChange={(event) => setIncident(event.target.value as SecurityIncident)}>{(Object.keys(SECURITY_INCIDENTS) as SecurityIncident[]).map((id) => <option key={id} value={id}>{local(locale, SECURITY_COPY[id].title)}</option>)}</Select>} prediction={{ prompt: copy(locale, "Which property or set of properties will the evidence show as affected?", "Bằng chứng sẽ cho thấy thuộc tính nào bị ảnh hưởng?"), choices: choiceSets.map((id) => ({ id, label: id.split("+").map((item) => local(locale, PROPERTY_LABELS[item as SecurityProperty])).join(" + ") })), correctChoiceId: propertySet }} scenes={scenes} />;
}

function ThreatLab({ locale }: { readonly locale: Paper1Locale }) {
  const defaults = { path: "phishing" as ThreatPath, applied: true };
  const [path, setPath] = useState<ThreatPath>(defaults.path);
  const [applied, setApplied] = useState(defaults.applied);
  const c = THREAT_COPY[path];
  const frames = threatProtectionFrames(path, applied);
  const outcome = applied ? c.protectedOutcome : c.unprotectedOutcome;
  const assetState = applied ? c.protectedState : c.unprotectedState;
  const risk = applied ? c.protectedRisk : c.unprotectedRisk;
  const correct = applied ? "reduced" : "continues";
  const scenes = frames.map((frame, index): Scene => ({ sceneId: `P1-L38-${path}-${applied ? "applied" : "omitted"}-${frame.id}`, title: [copy(locale, "Identify source and asset", "Xác định nguồn và tài sản"), copy(locale, "Follow the threat step", "Theo dõi bước đe dọa"), copy(locale, "Inspect the control checkpoint", "Quan sát checkpoint kiểm soát"), copy(locale, "Audit outcome and remaining risk", "Đánh giá kết quả và rủi ro còn lại")][index], explanation: [copy(locale, `${local(locale, c.actor)} targets ${local(locale, c.asset)}.`, `${local(locale, c.actor)} nhắm tới ${local(locale, c.asset)}.`), local(locale, c.step), applied ? copy(locale, `${local(locale, c.control)} acts ${local(locale, c.point)}.`, `${local(locale, c.control)} hoạt động ${local(locale, c.point)}.`) : copy(locale, `The relevant control is omitted at ${local(locale, c.boundary)}.`, `Biện pháp liên quan không được áp dụng tại ${local(locale, c.boundary)}.`), `${local(locale, outcome)}. ${copy(locale, "Remaining risk:", "Rủi ro còn lại:")} ${local(locale, risk)}.`][index], graphic: <EvidenceChain locale={locale} activeIds={frame.activeIds} ticket={frame.ticket} nodes={[{ id: "source", eyebrow: copy(locale, "SOURCE", "NGUỒN"), value: local(locale, c.actor) }, { id: "threat", eyebrow: copy(locale, "THREAT STEP", "BƯỚC ĐE DỌA"), value: local(locale, c.step) }, { id: "boundary", eyebrow: copy(locale, "TRUST BOUNDARY", "RANH GIỚI TIN CẬY"), value: local(locale, c.boundary) }, { id: "control", eyebrow: copy(locale, "CONTROL STATE", "TRẠNG THÁI KIỂM SOÁT"), value: index >= 2 ? (applied ? local(locale, c.control) : copy(locale, "Relevant control not applied", "Không áp dụng biện pháp liên quan")) : copy(locale, "Not inspected", "Chưa quan sát") }, { id: "asset-state", eyebrow: copy(locale, "ASSET STATE", "TRẠNG THÁI TÀI SẢN"), value: index === 3 ? local(locale, assetState) : copy(locale, "Not revealed", "Chưa mở") }]} />, receipt: [{ label: copy(locale, "Threat mechanism", "Cơ chế đe dọa"), value: local(locale, c.step), current: index === 1 }, { label: copy(locale, "Trust boundary", "Ranh giới tin cậy"), value: local(locale, c.boundary), current: index === 1 }, { label: copy(locale, "Relevant control", "Biện pháp liên quan"), value: local(locale, c.control) }, { label: copy(locale, "Control applied", "Đã áp dụng biện pháp"), value: bool(locale, applied), current: index === 2 }, { label: copy(locale, "Outcome", "Kết quả"), value: index >= 2 ? local(locale, outcome) : "—", current: index === 2 }, { label: copy(locale, "Protected asset state", "Trạng thái tài sản"), value: index === 3 ? local(locale, assetState) : "—", current: index === 3 }, { label: copy(locale, "Remaining risk", "Rủi ro còn lại"), value: index === 3 ? local(locale, risk) : "—", current: index === 3 }] }));
  return <Journey locale={locale} visualId="VIS-P1-L38" title={copy(locale, "Threat path and control checkpoint", "Đường đe dọa và checkpoint kiểm soát")} intro={copy(locale, "Place a relevant control at the boundary, inspect what changes and retain the residual risk.", "Đặt biện pháp phù hợp tại ranh giới, quan sát điều thay đổi và giữ lại rủi ro còn lại.")} stateKey={`${path}-${applied}`} onReset={() => { setPath(defaults.path); setApplied(defaults.applied); }} controls={<><Select id="p1-l38-path" label={copy(locale, "Threat/protection path", "Đường đe dọa/bảo vệ")} value={path} onChange={(event) => setPath(event.target.value as ThreatPath)}>{(Object.keys(THREAT_PATHS) as ThreatPath[]).map((id) => <option key={id} value={id}>{local(locale, THREAT_COPY[id].title)}</option>)}</Select><Select id="p1-l38-control" label={copy(locale, "Control state", "Trạng thái kiểm soát")} value={applied ? "applied" : "omitted"} onChange={(event) => setApplied(event.target.value === "applied")}><option value="applied">{copy(locale, "Applied", "Được áp dụng")}</option><option value="omitted">{copy(locale, "Not applied", "Không áp dụng")}</option></Select><div className={styles.conditionCard}><strong>{copy(locale, "Named boundary and control", "Ranh giới và biện pháp cụ thể")}</strong><span>{local(locale, c.boundary)} · {local(locale, c.control)}</span></div></>} prediction={{ prompt: copy(locale, "Will this authored route reach the harmful outcome under the displayed control state?", "Đường đã cho có đi tới kết quả gây hại với trạng thái kiểm soát đang hiển thị không?"), choices: [{ id: "reduced", label: copy(locale, "The relevant control interrupts or exposes the route", "Biện pháp liên quan ngắt hoặc làm lộ đường đe dọa") }, { id: "continues", label: copy(locale, "The threat route continues to the authored harmful state", "Đường đe dọa tiếp tục tới trạng thái gây hại đã cho") }, { id: "eliminated", label: copy(locale, "All risk is eliminated", "Mọi rủi ro bị loại bỏ") }], correctChoiceId: correct }} scenes={scenes} />;
}

function CheckDigitWork({ locale, visible }: { readonly locale: Paper1Locale; readonly visible: boolean }) {
  if (!visible) return null;
  const digits = [3, 1, 4, 1, 5, 9]; const weights = [7, 6, 5, 4, 3, 2];
  return <div className={styles.localScroll} tabIndex={0} aria-label={copy(locale, "Check digit calculation table", "Bảng tính chữ số kiểm tra")}><table><caption>{copy(locale, "Declared teaching algorithm", "Thuật toán minh họa đã khai báo")}</caption><thead><tr><th>{copy(locale, "Digit", "Chữ số")}</th>{digits.map((value, index) => <th key={index}>{value}</th>)}</tr></thead><tbody><tr><th scope="row">{copy(locale, "Weight", "Trọng số")}</th>{weights.map((value, index) => <td key={index}>{value}</td>)}</tr><tr><th scope="row">{copy(locale, "Product", "Tích")}</th>{digits.map((value, index) => <td key={index}>{value * weights[index]}</td>)}</tr></tbody></table><p>Σ = 84 · 84 mod 11 = 7 · 11 − 7 = <strong>4</strong></p></div>;
}

function ValidationLab({ locale }: { readonly locale: Paper1Locale }) {
  const defaults = { rule: "range" as ValidationRule, fixture: "passes" as ValidationFixture };
  const [rule, setRule] = useState<ValidationRule>(defaults.rule);
  const [fixture, setFixture] = useState<ValidationFixture>(defaults.fixture);
  const facts = VALIDATION_FIXTURES[rule][fixture];
  const c = RULE_COPY[rule];
  const frames = validationFrames(rule, fixture);
  const calculation = fixture === "passes" ? c.calculationPass : c.calculationFail;
  const limitation = fixture === "passes" ? c.limitPass : c.limitFail;
  const scenes = frames.map((frame, index): Scene => ({ sceneId: `P1-L39-${rule}-${fixture}-${frame.id}`, title: [copy(locale, "Receive the exact input", "Nhận input chính xác"), copy(locale, "Declare the rule", "Khai báo quy tắc"), copy(locale, "Apply the condition", "Áp dụng điều kiện"), copy(locale, "Return a qualified verdict", "Trả về kết luận có điều kiện")][index], explanation: [copy(locale, `${local(locale, c.field)} receives “${facts.input}”. No result is inferred yet.`, `${local(locale, c.field)} nhận “${facts.input}”. Chưa suy ra kết quả.`), local(locale, c.condition), local(locale, calculation), copy(locale, `${facts.pass ? "PASS" : "FAIL"}. ${local(locale, c.benefit)}. Limitation: ${local(locale, limitation)}.`, `${facts.pass ? "ĐẠT" : "KHÔNG ĐẠT"}. ${local(locale, c.benefit)}. Giới hạn: ${local(locale, limitation)}.`)][index], graphic: <div className={styles.modelStack}><EvidenceChain locale={locale} activeIds={frame.activeIds} ticket={frame.ticket} nodes={[{ id: "input", eyebrow: copy(locale, "INPUT", "INPUT"), value: JSON.stringify(facts.input) }, { id: "rule", eyebrow: copy(locale, "DECLARED RULE", "QUY TẮC ĐÃ KHAI BÁO"), value: index >= 1 ? local(locale, c.condition) : copy(locale, "Not applied", "Chưa áp dụng") }, { id: "calculation", eyebrow: copy(locale, "TEST", "PHÉP KIỂM TRA"), value: index >= 2 ? local(locale, calculation) : copy(locale, "Not revealed", "Chưa mở") }, { id: "verdict", eyebrow: copy(locale, "QUALIFIED VERDICT", "KẾT LUẬN CÓ ĐIỀU KIỆN"), value: index === 3 ? (facts.pass ? "PASS" : "FAIL") : copy(locale, "Not revealed", "Chưa mở") }]} /><CheckDigitWork locale={locale} visible={rule === "check-digit" && index >= 2} /></div>, receipt: [{ label: copy(locale, "Classification", "Phân loại"), value: copy(locale, "Validation", "Validation") }, { label: copy(locale, "Field purpose", "Mục đích trường"), value: local(locale, c.field), current: index === 0 }, { label: copy(locale, "Input", "Input"), value: JSON.stringify(facts.input), current: index === 0 }, { label: copy(locale, "Condition", "Điều kiện"), value: index >= 1 ? local(locale, c.condition) : "—", current: index === 1 }, { label: copy(locale, "Calculation", "Phép tính/so sánh"), value: index >= 2 ? local(locale, calculation) : "—", current: index === 2 }, { label: copy(locale, "Verdict", "Kết luận"), value: index === 3 ? (facts.pass ? copy(locale, "PASS", "ĐẠT") : copy(locale, "FAIL", "KHÔNG ĐẠT")) : "—", current: index === 3 }, { label: copy(locale, "Integrity benefit", "Lợi ích toàn vẹn"), value: index === 3 ? local(locale, c.benefit) : "—", current: index === 3 }, { label: copy(locale, "Limitation", "Giới hạn"), value: index === 3 ? local(locale, limitation) : "—", current: index === 3 }] }));
  const setRuleAndResetFixture = (next: ValidationRule) => { setRule(next); setFixture("passes"); };
  return <Journey locale={locale} visualId="VIS-P1-L39" title={copy(locale, "Seven-rule validation gatebench", "Bàn validation với bảy quy tắc")} intro={copy(locale, "Apply the seven checks required by the 2026 syllabus and keep valid separate from factually correct.", "Áp dụng bảy kiểm tra của syllabus 2026 và phân biệt hợp lệ với đúng trong thực tế.")} stateKey={`${rule}-${fixture}`} onReset={() => { setRule(defaults.rule); setFixture(defaults.fixture); }} controls={<><Select id="p1-l39-rule" label={copy(locale, "Validation rule", "Quy tắc validation")} value={rule} onChange={(event) => setRuleAndResetFixture(event.target.value as ValidationRule)}>{(Object.keys(VALIDATION_FIXTURES) as ValidationRule[]).map((id) => <option key={id} value={id}>{local(locale, RULE_COPY[id].title)}</option>)}</Select><Select id="p1-l39-fixture" label={copy(locale, "Input fixture", "Tình huống input")} value={fixture} onChange={(event) => setFixture(event.target.value as ValidationFixture)}><option value="passes">A · {JSON.stringify(VALIDATION_FIXTURES[rule].passes.input)}</option><option value="fails">B · {JSON.stringify(VALIDATION_FIXTURES[rule].fails.input)}</option></Select><div className={styles.conditionCard}><strong>{copy(locale, "Condition visible before prediction", "Điều kiện hiển thị trước dự đoán")}</strong><span>{local(locale, c.condition)}</span></div></>} prediction={{ prompt: copy(locale, "Under the displayed rule, will this exact input pass or fail?", "Theo quy tắc đang hiển thị, input này sẽ đạt hay không đạt?"), choices: [{ id: "pass", label: copy(locale, "PASS", "ĐẠT") }, { id: "fail", label: copy(locale, "FAIL", "KHÔNG ĐẠT") }], correctChoiceId: facts.pass ? "pass" : "fail" }} scenes={scenes} />;
}

function BitRows({ locale, source, received, changedPositions, matrix }: { readonly locale: Paper1Locale; readonly source: readonly string[]; readonly received: readonly string[]; readonly changedPositions: readonly string[]; readonly matrix: boolean }) {
  const changed = new Set(changedPositions);
  const row = (bits: string, rowIndex: number, receivedRow: boolean) => <div className={styles.bitRow} role="row">{bits.split("").map((bit, columnIndex) => { const id = matrix ? `row-${rowIndex}-column-${columnIndex}` : `bit-${columnIndex}`; return <span role="cell" key={columnIndex} data-changed={receivedRow && changed.has(id) || undefined} aria-label={copy(locale, `${receivedRow ? "Received" : "Source"} row ${rowIndex}, bit ${columnIndex}: ${bit}${receivedRow && changed.has(id) ? ", changed" : ""}`, `${receivedRow ? "Nhận" : "Nguồn"} hàng ${rowIndex}, bit ${columnIndex}: ${bit}${receivedRow && changed.has(id) ? ", đã đổi" : ""}`)}>{bit}</span>; })}</div>;
  return <div className={styles.bitCompare} role="table" aria-label={copy(locale, "Source and received bit comparison", "So sánh bit nguồn và bit nhận")}><section><strong>{copy(locale, "SOURCE", "NGUỒN")}</strong>{source.map((bits, index) => <div key={index}>{row(bits, index, false)}</div>)}</section><section><strong>{copy(locale, "ENTERED / RECEIVED", "ĐÃ NHẬP / NHẬN")}</strong>{received.map((bits, index) => <div key={index}>{row(bits, index, true)}</div>)}</section></div>;
}

function VerificationGraphic({ locale, method, fixture, index, activeIds, ticket }: { readonly locale: Paper1Locale; readonly method: VerificationMethod; readonly fixture: VerificationFixture; readonly index: number; readonly activeIds: readonly string[]; readonly ticket: string }) {
  const facts = verificationFacts(method, fixture);
  const source = facts.source.join(method === "block-parity" ? " / " : " · ");
  const received = facts.enteredOrReceived.join(method === "block-parity" ? " / " : " · ");
  const recomputed = Array.isArray(facts.recomputedCheck) ? facts.recomputedCheck.join(" · ") : String(facts.recomputedCheck);
  return <div className={styles.modelStack}><EvidenceChain locale={locale} activeIds={activeIds} ticket={ticket} nodes={[{ id: "source", eyebrow: copy(locale, "SOURCE", "NGUỒN"), value: source }, { id: "check-data", eyebrow: copy(locale, "CHECK RULE / DATA", "QUY TẮC / DỮ LIỆU KIỂM TRA"), value: local(locale, METHOD_CONVENTION[method]) }, { id: "received", eyebrow: copy(locale, "ENTERED / RECEIVED", "ĐÃ NHẬP / NHẬN"), value: index >= 1 ? received : copy(locale, "Not received", "Chưa nhận") }, { id: "recomputed-check", eyebrow: copy(locale, "RECOMPUTED CHECK", "KIỂM TRA LẠI"), value: index >= 2 ? recomputed : copy(locale, "Not revealed", "Chưa mở") }, { id: "verdict", eyebrow: copy(locale, "QUALIFIED VERDICT", "KẾT LUẬN CÓ ĐIỀU KIỆN"), value: index === 3 ? (facts.detected ? copy(locale, "DETECTED", "PHÁT HIỆN") : copy(locale, "NOT DETECTED", "KHÔNG PHÁT HIỆN")) : copy(locale, "Not revealed", "Chưa mở") }]} />{(method === "byte-parity" || method === "block-parity") && index >= 1 ? <div className={styles.localScroll} tabIndex={0}><BitRows locale={locale} source={facts.source} received={facts.enteredOrReceived} changedPositions={facts.changedPositions} matrix={method === "block-parity"} />{method === "block-parity" && index >= 2 ? <p>{copy(locale, "Failed rows", "Hàng lỗi")}: {join(facts.failedRows.map(String))} · {copy(locale, "Failed columns", "Cột lỗi")}: {join(facts.failedColumns.map(String))}</p> : null}</div> : null}</div>;
}

function VerificationLab({ locale }: { readonly locale: Paper1Locale }) {
  const defaults = { method: "byte-parity" as VerificationMethod, fixture: "one-flip" as VerificationFixture };
  const [method, setMethod] = useState<VerificationMethod>(defaults.method);
  const [fixture, setFixture] = useState<VerificationFixture>(defaults.fixture);
  const facts = verificationFacts(method, fixture);
  const frames = verificationFrames(method, fixture);
  const recomputed = Array.isArray(facts.recomputedCheck) ? facts.recomputedCheck.join(" · ") : String(facts.recomputedCheck);
  const limitation = method === "visual" ? copy(locale, "A visual check depends on the source and human observation.", "Kiểm tra trực quan phụ thuộc vào nguồn và quan sát của con người.") : method === "double-entry" ? (fixture === "same-wrong-twice" ? copy(locale, "The same wrong value entered twice can match and remain undetected.", "Cùng một giá trị sai nhập hai lần có thể khớp và không bị phát hiện.") : copy(locale, "Matching entries reduce transcription risk but do not prove source correctness.", "Hai lần nhập khớp giúp giảm rủi ro chép sai nhưng không chứng minh nguồn đúng.")) : method === "byte-parity" ? (fixture === "two-flips" ? copy(locale, "An even number of flipped bits can preserve byte parity.", "Số bit bị đảo chẵn có thể giữ nguyên parity byte.") : copy(locale, "Byte parity detects a mismatch but does not locate or repair the bit.", "Parity byte phát hiện sai lệch nhưng không định vị hoặc sửa bit.")) : method === "block-parity" ? (fixture === "rectangle" ? copy(locale, "A four-corner pattern can preserve every row and column parity.", "Mẫu bốn góc có thể giữ nguyên parity của mọi hàng và cột.") : copy(locale, "A single-bit intersection does not generalise to arbitrary multiple errors.", "Giao điểm một bit không áp dụng cho mọi lỗi nhiều bit.")) : (fixture === "compensating" ? copy(locale, "+1 and −1 changes can preserve this modulo-256 checksum.", "Hai thay đổi +1 và −1 có thể giữ nguyên checksum modulo 256 này.") : copy(locale, "A checksum mismatch does not locate or repair an error.", "Checksum khác không định vị hoặc sửa lỗi."));
  const scenes = frames.map((frame, index): Scene => ({ sceneId: `P1-L40-${method}-${fixture}-${frame.id}`, title: [copy(locale, "Fix the source and checking rule", "Cố định nguồn và quy tắc kiểm tra"), copy(locale, "Enter or transmit the fixture", "Nhập hoặc truyền tình huống"), copy(locale, "Recompute and compare", "Tính lại và so sánh"), copy(locale, "State detection and its limit", "Nêu kết quả phát hiện và giới hạn")][index], explanation: [copy(locale, `Source: ${facts.source.join(" · ")}. Rule: ${local(locale, METHOD_CONVENTION[method])}.`, `Nguồn: ${facts.source.join(" · ")}. Quy tắc: ${local(locale, METHOD_CONVENTION[method])}.`), copy(locale, `Entered/received: ${facts.enteredOrReceived.join(" · ")}. Changed positions: ${join(facts.changedPositions)}.`, `Đã nhập/nhận: ${facts.enteredOrReceived.join(" · ")}. Vị trí đổi: ${join(facts.changedPositions)}.`), copy(locale, `Recomputed check: ${recomputed}.`, `Kiểm tra tính lại: ${recomputed}.`), copy(locale, `${facts.detected ? "DETECTED" : "NOT DETECTED"}. ${limitation}`, `${facts.detected ? "PHÁT HIỆN" : "KHÔNG PHÁT HIỆN"}. ${limitation}`)][index], graphic: <VerificationGraphic locale={locale} method={method} fixture={fixture} index={index} activeIds={frame.activeIds} ticket={frame.ticket} />, receipt: [{ label: copy(locale, "Method", "Phương pháp"), value: local(locale, METHOD_LABELS[method]), current: index === 0 }, { label: copy(locale, "Convention", "Quy ước"), value: local(locale, METHOD_CONVENTION[method]), current: index === 0 }, { label: copy(locale, "Source", "Nguồn"), value: facts.source.join(" · ") }, { label: copy(locale, "Entered/received", "Đã nhập/nhận"), value: index >= 1 ? facts.enteredOrReceived.join(" · ") : "—", current: index === 1 }, { label: copy(locale, "Changed positions", "Vị trí đổi"), value: index >= 1 ? join(facts.changedPositions) : "—", current: index === 1 }, { label: copy(locale, "Recomputed check", "Kiểm tra tính lại"), value: index >= 2 ? recomputed : "—", current: index === 2 }, { label: copy(locale, "Failed rows / columns", "Hàng / cột lỗi"), value: index >= 2 && method === "block-parity" ? `${join(facts.failedRows.map(String))} / ${join(facts.failedColumns.map(String))}` : "—", current: index === 2 && method === "block-parity" }, { label: copy(locale, "Detected", "Phát hiện"), value: index === 3 ? bool(locale, facts.detected) : "—", current: index === 3 }, { label: copy(locale, "Correctable in this fixture", "Có thể sửa trong tình huống này"), value: index === 3 ? bool(locale, facts.correctableUnderFixture) : "—", current: index === 3 }, { label: copy(locale, "Limitation", "Giới hạn"), value: index === 3 ? limitation : "—", current: index === 3 }] }));
  const setMethodAndFixture = (next: VerificationMethod) => { setMethod(next); setFixture(VERIFICATION_FIXTURES[next][0]); };
  return <Journey locale={locale} visualId="VIS-P1-L40" title={copy(locale, "Entry verification and transfer-check bench", "Bàn verification khi nhập và kiểm tra khi truyền")} intro={copy(locale, "Compare entry methods with parity and checksum, including an exact error pattern each method can miss.", "So sánh phương pháp nhập với parity và checksum, gồm một mẫu lỗi chính xác mà mỗi phương pháp có thể bỏ sót.")} stateKey={`${method}-${fixture}`} onReset={() => { setMethod(defaults.method); setFixture(defaults.fixture); }} controls={<><Select id="p1-l40-method" label={copy(locale, "Method", "Phương pháp")} value={method} onChange={(event) => setMethodAndFixture(event.target.value as VerificationMethod)}>{(Object.keys(VERIFICATION_FIXTURES) as VerificationMethod[]).map((id) => <option key={id} value={id}>{local(locale, METHOD_LABELS[id])}</option>)}</Select><Select id="p1-l40-fixture" label={copy(locale, "Method-specific fixture", "Tình huống riêng của phương pháp")} value={fixture} onChange={(event) => setFixture(event.target.value as VerificationFixture)}>{VERIFICATION_FIXTURES[method].map((id) => <option key={id} value={id}>{local(locale, FIXTURE_LABELS[id])}</option>)}</Select><div className={styles.conditionCard}><strong>{copy(locale, "Declared convention", "Quy ước đã khai báo")}</strong><span>{local(locale, METHOD_CONVENTION[method])}</span></div></>} prediction={{ prompt: copy(locale, "Will this exact method and fixture detect a mismatch?", "Phương pháp và tình huống chính xác này có phát hiện sai lệch không?"), choices: [{ id: "detected", label: copy(locale, "Detected", "Phát hiện") }, { id: "not-detected", label: copy(locale, "Not detected", "Không phát hiện") }], correctChoiceId: facts.detected ? "detected" : "not-detected" }} scenes={scenes} />;
}

export function Chapter6VisualLab({ lessonId, locale }: { readonly lessonId: string; readonly locale: Paper1Locale }) {
  if (lessonId === "P1-L37") return <SecurityLab locale={locale} />;
  if (lessonId === "P1-L38") return <ThreatLab locale={locale} />;
  if (lessonId === "P1-L39") return <ValidationLab locale={locale} />;
  if (lessonId === "P1-L40") return <VerificationLab locale={locale} />;
  return null;
}
